bind-key R source-file ~/.tmux.conf

setw -g mode-keys vi

set-option -g default-terminal screen-256color
bind-key space next-window
bind-key bspace previous-window
bind-key enter next-layout

# vim-like screen moving and splitting
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# theme
# run-shell "~/.tmux/themes/dracula/dracula.tmux"
# set -g @dracula-show-battery false
# set -g @dracula-show-network false
# set -g @dracula-show-weather false
# set -g @dracula-border-contrast true

