#!/bin/bash

case "$(uname -n)" in
    'rgertenbach3')
        swaylock --image=~/Pictures/pexels-francesco-ungaro-2915997.png
        ;;
    'rgertenbach.mtv.corp.google.com')
        swaylock -i DP-2:~/Pictures/DP-2.png -i DP-4:~/Pictures/DP-4.png
        ;;
    'nibor')
        swaylock -i DP-2:~/Pictures/wallpapers/DP-2.png -i DP-1:~/Pictures/wallpapers/DP-1.png
        ;;
    *)
        swaylock
        ;;
esac
